version: "3"
services:
  postgres:
    image: postgres:10.6
    environment:
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_USER=${DB_USER}
    ports:
    - "5432:5432"
    volumes:
    - ./.db_data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql